### ISSUE TITLE
paste setting error

### ISSUE THREAD

**Issue by murakotaro4** [Shirkit/AdditionalPasteSettings#2]
I report it because an error occurred. I do not know clearly what kind of operation occurred, but I think that it occurred when trying to paste the setting.
[https://gyazo.com/4f5ddf898bbc2cc30efa052be83acbe5](url)

**Comment by pa-philos** [comment]
Hey @murakotaro4 I fixed this issue, thanks for the report!
I'll take a look on the other problem you had!

**Comment by murakotaro4** [comment]
Thank you for fixing!

I will check it later.


2018年6月27日(水) 2:00 Shirkit <notifications@github.com>:

**Comment by pa-philos** [comment]
I haven't release the new version yet, I need someone to test on multiplayer with me the other bug.
