### ISSUE TITLE
Version 0.50 can not be downloaded.

### ISSUE THREAD

**Issue by murakotaro4** [Shirkit/AdditionalPasteSettings#3]
Can I download the latest version 0.50?
I can only download 0.41 on the FactorioMods page.
[https://mods.factorio.com/mod/additional-paste-settings](url)

**Comment by pa-philos** [comment]
hey,

I wanted to test 0.5.0 with you before releasing to make sure it does work
in Multiplayer.

I can meet you in Discord.

**Comment by murakotaro4** [comment]
I can test today after 14 o'clock Tokyo time.
Let’s meet on Discord.

2018年7月2日(月) 2:10 Shirkit <notifications@github.com>:

> hey,
>
> I wanted to test 0.5.0 with you before releasing to make sure it does work
> in Multiplayer.
>
> I can meet you in Discord.
>

**Comment by Shirkit** [comment]
That's pretty impossible for me, the best timing is or 09-10 o'clock or 21-22 o'clock Tokyo time.

**Comment by pa-philos** [comment]
That's pretty impossible for me, I'm sleeping at that time. The best timing is or 09-10 o'clock or 21-22 o'clock Tokyo time.
